FROM node:18.16.0-alpine as tres-build-base

WORKDIR /app
COPY ./site/ /app
RUN npm config delete proxy
RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=tres-build-base /app/build /usr/share/nginx/html
