
version: '2'

services:
  docker-ui-api:
    container_name: docker-ui-api
    build:
      context: .
      dockerfile: ./Dockerfile.api.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  docker-ui-site:
    container_name: docker-ui-site
    build:
      context: .
      dockerfile: ./Dockerfile.site.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
