
version: '2'

services:
  docker-ui-api:
    container_name: docker-ui-api
    build:
      context: .
      dockerfile: ./Dockerfile.api.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - $API_HOST
    networks:
      - docker-ui
    environment:
      - API_DEBUG=$API_DEBUG
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT

  docker-ui-site:
    container_name: docker-ui-site
    build:
      context: .
      dockerfile: ./Dockerfile.site.yaml
    ports:
      - "80:80"
    networks:
      - docker-ui
    environment:
      - SITE_API_HOST="docker-ui-api:$API_PORT"

networks:
  docker-ui:
